version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: natixe28/boutique-noname:production
    depends_on:
      - db
    env_file:
      - .env
    container_name: boutique-noname
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
      - "8888:8888"
      - "5432:5432"
volumes:
  db-data:
