version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: natixe28/boutique-noname:production
    depends_on:
      - db
    container_name: boutique-noname
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
    - app-data:/app
    ports:
      - "8888:8888"


  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - app-data:/app
    restart: unless-stopped

volumes:
  db-data:
  caddy_data:
  caddy_config:
  app-data: