version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: natixe28/boutique-noname:production
    depends_on:
      - db
    container_name: boutique-noname
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
      - "8888:8888"
volumes:
  db-data:
