version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: natixe28/boutique-noname:production
    depends_on:
      - db
    container_name: boutique-noname
    restart: always
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db-data:
  caddy_data:
  caddy_config: